# BLOODTHIRSTY =
{
    'name': 'bloodthirsty',
    'nice_name': 'Bloodthirsty',
    'dictionary': """
    1. eager
    for or marked by the shedding of blood,
    violence,
    or killing
    """,
    'verses': {
        1: {
            'notes': 'The Lord has a sword',
            'book': 'Isaiah',
            'chapter': 34,
            'verse': [6],
            'search': ['vengeance'],
        },
        2: {
            'notes': 'It is blood that makes atonement',
            'book': 'Leviticus',
            'chapter': 17,
            'verse': [11],
            'search': ['if you bleed God will be happy'],
        },
        3: {
            'notes': 'Drink the blood',
            'book': 'Ezekiel',
            'chapter': 39,
            'verse': [17, 18],
            'search': ['drink blood as a sacrifice because god sacrifices for you'],
        },
        4: {
            'notes': 'His sword is soaked with blood',
            'book': 'Isaiah',
            'chapter': 34,
            'verse': [5, 6, 7],
            'search': ['god\'s sword is bloody from killing animals'],
        },
        5: {
            'notes': 'Drunk with blood',
            'book': 'Jeremiah',
            'chapter': 46,
            'verse': [10],
            'search': ['god\'s sword is drunk with blood'],
        },
        6: {
            'notes': '"My arrows are drunk with blood." Praise God!',
            'book': 'Deuteronomy',
            'chapter': 32,
            'verse': [39, 40, 41, 42, 43],
            'search': ['people should be happy that god is so bloodthirsty'],
        },
        7: {
            'notes': 'Mountains soaked with blood',
            'book': 'Isaiah',
            'chapter': 34,
            'verse': [2, 3],
            'search': ['"The Lord is angry with all nations"'],
        },
        8: {
            'notes': 'God wants YOU to shed blood',
            'book': 'Jeremiah',
            'chapter': 48,
            'verse': [1, 10],
            'search': ['"cursed is he who keeps back his sword from bloodshed"'],
        },
        9: {
            'notes': 'Blood required at your hand',
            'book': 'Ezekiel',
            'chapter': 3,
            'verse': [16, 20],
            'search': ['I kill, you kill, we all kill!'],
        },
        10: {
            'notes': 'Pestilence and blood',
            'book': 'Ezekiel',
            'chapter': 5,
            'verse': [17],
            'search': ['you\'ll get REALLY sick and then I\'ll kill you'],
        },
        11: {
            'notes': 'More pestilence and blood',
            'book': 'Ezekiel',
            'chapter': 14,
            'verse': [19],
            'search': ['blood then pestilence'],
        },
        12: {
            'notes': 'Blood upon (female) Jerusalem',
            'book': 'Ezekiel',
            'chapter': 16,
            'verse': [38],
            'search': ['if you\'re a divorced woman I\'ll judge you and bring blood upon you'],
        },
        13: {
            'notes': 'Blood shall pursue you',
            'book': 'Ezekiel',
            'chapter': 35,
            'verse': [6],
            'search': ['can\'t get away from all of the blood'],
        },
        14: {
            'notes': 'Drench Egypt with blood',
            'book': 'Ezekiel',
            'chapter': 32,
            'verse': [6],
            'search': ['bloody land'],
        },
        15: {
            'notes': 'Blood in the streets',
            'book': 'Ezekiel',
            'chapter': 28,
            'verse': [22, 23],
            'search': ['they\'ll know I\'m god because I\'ll kill a lot of people'],
        },
        16: {
            'notes': 'Pleading with pestilence and blood',
            'book': 'Ezekiel',
            'chapter': 38,
            'verse': [22, 23],
            'search': ['blood, hail and brimstone'],
        },
        17: {
            'notes': 'Blood on a rock',
            'book': 'Ezekiel',
            'chapter': 24,
            'verse': [8],
            'search': ['bloody rock'],
        },
        18: {
            'notes': 'Blood on the wall',
            'book': '2 Kings',
            'chapter': 9,
            'verse': [33, 34, 35, 36, 37],
            'search': ['woman thrown down and trampled beyond recognition'],
        },
        19: {
            'notes': 'Incest blood',
            'book': 'Leviticus',
            'chapter': 20,
            'verse': [11, 12],
            'search': ['incest is punishable by death'],
        },
        20: {
            'notes': 'Homosexual blood',
            'book': 'Leviticus',
            'chapter': 20,
            'verse': [13],
            'search': ['homosexuality is punishable by death'],
        },
        21: {
            'notes': 'Bestiality blood',
            'book': 'Leviticus',
            'chapter': 20,
            'verse': [16],
            'search': ['both the woman and beast shall be killed'],
        },
        22: {
            'notes': 'Medium blood',
            'book': 'Leviticus',
            'chapter': 20,
            'verse': [27],
            'search': ['wizards and mediums will be killed'],
        },
        23: {
            'notes': 'Children\'s blood',
            'book': 'Leviticus',
            'chapter': 20,
            'verse': [9],
            'search': ['children die for cursing their parents'],
        },
        24: {
            'notes': 'King David\'s last word, spoken to his son Solomon',
            'book': '1 Kings',
            'chapter': 2,
            'verse': [9],
            'search': ['smash a guy\'s head in'],
        },
        25: {
            'notes': 'Blood and fire',
            'book': 'Joel',
            'chapter': 2,
            'verse': [30],
            'search': ['blood and fire'],
        },
        26: {
            'notes': 'Blood poured out like dust',
            'book': 'Zephaniah',
            'chapter': 1,
            'verse': [17],
            'search': ['the entrails of sinners will be poured out like dung'],
        },
        27: {
            'notes': 'Blood poured out on the earth',
            'book': 'Isaiah',
            'chapter': 63,
            'verse': [6],
            'search': ['God trod on people in his anger'],
        },
        28: {
            'notes': 'Slaughter without mercy',
            'book': 'Lamentations',
            'chapter': 2,
            'verse': [17, 18, 19, 20, 21, 22],
            'search': ['God slaughters without pity'],
        },
        29: {
            'notes': 'Death for hitting your parents',
            'book': 'Exodus',
            'chapter': 21,
            'verse': [15],
            'search': ['death for striking your parents'],
        },
        30: {
            'notes': 'Death for prostitution',
            'book': 'Leviticus',
            'chapter': 21,
            'verse': [9],
            'search': ['if a priest\'s daughter becomes a prostitute she must burn to death'],
        },
        31: {
            'notes': 'Death for adultery',
            'book': 'Leviticus',
            'chapter': 20,
            'verse': [10],
            'search': ['both parties shall be put to death'],
        },
        32: {
            'notes': 'Death for disobeying the clergy',
            'book': 'Deuteronomy',
            'chapter': 17,
            'verse': [12],
            'search': ['if you show contempt for a judge you shall be put to death'],
        },
        33: {
            'notes': 'Death to nonbelievers',
            'book': '2 Chronicles',
            'chapter': 15,
            'verse': [13],
            'search': ['kids and adults put to death'],
        },
        34: {
            'notes': 'Death to other religious followers',
            'book': 'Exodus',
            'chapter': 22,
            'verse': [20],
            'search': ['sacrifices to another god will get you killed'],
        },
        35: {
            'notes': 'Death for blasphemy',
            'book': 'Leviticus',
            'chapter': 24,
            'verse': [13, 14, 15, 16],
            'search': ['people who blashpeme should be stoned to death'],
        },
        36: {
            'notes': 'Death to false prophets',
            'book': 'Deuteronomy',
            'chapter': 18,
            'verse': [20],
            'search': ['death to false prophets'],
        },
        37: {
            'notes': 'Death to non-priests who approach the Tabernacle',
            'book': 'Numbers',
            'chapter': 1,
            'verse': [51],
            'search': ['unworthy people near sacred places shall be put to death'],
        },
        38: {
            'notes': 'Death to any woman who is not a virgin on her wedding night',
            'book': 'Deuteronomy',
            'chapter': 22,
            'verse': [20, 21],
            'search': ['misogyny'],
        },
        39: {
            'notes': 'Death to children of those hostile to God',
            'book': 'Leviticus',
            'chapter': 26,
            'verse': [21, 22],
            'search': ['wild animals will take your children away'],
        },
        40: {
            'notes': 'Death to a whole town that worships another god',
            'book': 'Deuteronomy',
            'chapter': 13,
            'verse': [12, 16],
            'search': ['jealous'],
        },
        41: {
            'notes': 'Death to Babylon',
            'book': 'Jeremiah',
            'chapter': 50,
            'verse': [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
            'search': ['time for them to be punished'],
        },
        42: {
            'notes': 'Death to the Assyrians',
            'book': '2 Kings',
            'chapter': 19,
            'verse': [35],
            'search': ['the angel of the lord slew 185,000'],
        },
        43: {
            'notes': 'Queen Esther demanded the slaughter of Persians',
            'book': 'Esther',
            'chapter': 9,
            'verse': [5, 6],
            'search': ['so much killing'],
        },
        44: {
            'notes': 'Queen Esther demanded the slaughter of Persians, but she wanted more joyful death',
            'book': 'Esther',
            'chapter': 9,
            'verse': [13, 14, 15, 16, 17],
            'search': ['impaling'],
        },
        45: {
            'notes': 'Death to the prophets of Baal',
            'book': '1 Kings',
            'chapter': 18,
            'verse': [39, 40],
            'search': ['let no one escape'],
        },
        46: {
            'notes': 'Death in the streets',
            'book': 'Ezekiel',
            'chapter': 9,
            'verse': [4, 5, 6],
            'search': ['"slay utterly old and young, both maids and little children and women'],
        },
        47: {
            'notes': 'Death in the mountains, hills, valleys, and waterways',
            'book': 'Ezekiel',
            'chapter': 35,
            'verse': [7, 8],
            'search': ['the dead are everywhere'],
        },
        48: {
            'notes': 'Kill your brothers and friends to get a blessing',
            'book': 'Exodus',
            'chapter': 32,
            'verse': [27, 28, 29],
            'search': ['sacrifice people you love'],
        },
        49: {
            'notes': 'Decapitate those who happen to worship the wrong god',
            'book': 'Numbers',
            'chapter': 25,
            'verse': [4, 5],
            'search': ['God likes severed heads'],
        },
        50: {
            'notes': 'Death by thirds',
            'book': 'Ezekiel',
            'chapter': 5,
            'verse': [11, 12, 13, 14, 15, 16],
            'search': ['two thirds of your group will die by the sword or from pestilence'],
        },
        51: {
            'notes': 'Pacifist killed by a lion',
            'book': '1 Kings',
            'chapter': 20,
            'verse': [35, 36],
            'search': ['if you don\'t hit me a lion will eat you'],
        },
        52: {
            'notes': 'God will "tear like a lion"',
            'book': 'Hosea',
            'chapter': 13,
            'verse': [4, 5, 6, 7, 8, 9],
            'search': ['Israel "forgot" God so he\'ll attack and rip the Israelites open'],
        },
        53: {
            'notes': 'Slaughter a lamb for every sinner',
            'book': '2 Chronicles',
            'chapter': 30,
            'verse': [17],
            'search': ['poor lambs'],
        },
        54: {
            'notes': 'Smashing pep talk to Israel: "You are my battle axe"',
            'book': 'Jeremiah',
            'chapter': 51,
            'verse': [20, 21, 22, 23],
            'search': ['using people to destroy kingdoms'],
        },
        55: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Exodus',
            'chapter': 29,
            'verse': [15, 16],
            'search': ['poor animals'],
        },
        56: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 1,
            'verse': 5,
            'search': ['poor animals'],
        },
        57: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 1,
            'verse': [10, 11],
            'search': ['poor animals'],
        },
        58: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 1,
            'verse': [15],
            'search': ['poor animals'],
        },
        59: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 3,
            'verse': [2],
            'search': ['poor animals'],
        },
        60: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 3,
            'verse': [8],
            'search': ['poor animals'],
        },
        61: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 3,
            'verse': [13],
            'search': ['poor animals'],
        },
        62: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [5],
            'search': ['poor animals'],
        },
        63: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [7],
            'search': ['poor animals'],
        },
        64: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [16, 17, 18],
            'search': ['poor animals'],
        },
        65: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 5,
            'verse': [9],
            'search': ['poor animals'],
        },
        66: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 7,
            'verse': [14],
            'search': ['poor animals'],
        },
        67: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 8,
            'verse': [30],
            'search': ['poor animals'],
        },
        68: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 9,
            'verse': [12],
            'search': ['poor animals'],
        },
        69: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 9,
            'verse': [18],
            'search': ['poor animals'],
        },
        70: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 16,
            'verse': [27],
            'search': ['poor animals'],
        },
        71: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Leviticus',
            'chapter': 17,
            'verse': [6],
            'search': ['poor animals'],
        },
        72: {
            'notes': 'Bloody animal sacrifice',
            'book': 'Numbers',
            'chapter': 18,
            'verse': [17],
            'search': ['poor animals'],
        },
        73: {
            'notes': 'Bloody animal sacrifice',
            'book': '2 Chronicles',
            'chapter': 29,
            'verse': [22, 23, 24],
            'search': ['poor animals'],
        },
        74: {
            'notes': 'Fingers dripping with blood',
            'book': 'Exodus',
            'chapter': 29,
            'verse': [10, 12],
            'search': ['bloody fingers'],
        },
        75: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [6],
            'search': ['bloody fingers'],
        },
        76: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [17],
            'search': ['bloody fingers'],
        },
        77: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [25],
            'search': ['bloody fingers'],
        },
        78: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [30],
            'search': ['bloody fingers'],
        },
        79: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 4,
            'verse': [34],
            'search': ['bloody fingers'],
        },
        80: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 8,
            'verse': [15],
            'search': ['bloody fingers'],
        },
        81: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 8,
            'verse': [23, 24],
            'search': ['bloody fingers'],
        },
        82: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 9,
            'verse': [9],
            'search': ['bloody fingers'],
        },
        83: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 14,
            'verse': [14],
            'search': ['bloody fingers'],
        },
        84: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 16,
            'verse': [14, 15],
            'search': ['bloody fingers'],
        },
        85: {
            'notes': 'Fingers dripping with blood',
            'book': 'Leviticus',
            'chapter': 16,
            'verse': [18, 19],
            'search': ['bloody fingers'],
        },
        86: {
            'notes': 'Fingers dripping with blood',
            'book': 'Numbers',
            'chapter': 19,
            'verse': [1, 2, 3, 4, 5],
            'search': ['bloody fingers'],
        },
        87: {
            'notes': 'Fingers dripping with blood',
            'book': '2 Chronicles',
            'chapter': 35,
            'verse': [11],
            'search': ['bloody fingers'],
        }
    }
}
