# JEALOUS = 
{
    'name': 'jealous',
    'nice_name': 'Jealous',
    'dictionary': """
    1. hostile toward a rival or one believed to enjoy an advantage: envious.
    2. intolerant of rivalry or unfaithfulness.
    3. vigilant in guarding a possession.
    """,
    'verses': {
        1: {
            'notes': 'Avenging and wrathful',
            'book': 'Nahum',
            'chapter': 1,
            'verse': [2],
            'search': ['why would god be jealous if He created everything'],
        },
        2: {
            'notes': 'No one can approach God, on penalty of death',
            'book': 'Exodus',
            'chapter': 19,
            'verse': [12, 13],
            'search': ['no one better come near me'],
        },
        3: {
            'notes': 'No one can look at God',
            'book': 'Exodus',
            'chapter': 19,
            'verse': [21, 22],
            'search': ['just looking at god is punishable'],
        },
        4: {
            'notes': 'No other gods',
            'book': 'Exodus',
            'chapter': 20,
            'verse': [1, 2, 3],
            'search': ['how could there be other gods that god himself did not create?'],
        },
        5: {
            'notes': 'I am a jealous god',
            'book': 'Exodus',
            'chapter': 20,
            'verse': [4, 5, 6],
            'search': ['punishing children for the inequity of parents...but showing steadfast love...'],
        },
        6: {
            'notes': 'he names himself Jealous',
            'book': 'Exodus',
            'chapter': 34,
            'verse': [14, 15],
            'search': ['whose name is Jealous'],
        },
        7: {
            'notes': 'Destructive jealousy',
            'book': 'Deuteronomy',
            'chapter': 6,
            'verse': [15],
            'search': ['he created you...but he\'ll destroy you because he\'s jealous'],
        },
        8: {
            'notes': 'Burning jealousy',
            'book': 'Deuteronomy',
            'chapter': 4,
            'verse': [24],
            'search': ['better get that looked at'],
        },
        9: {
            'notes': 'Unforgiving jealousy',
            'book': 'Joshua',
            'chapter': 24,
            'verse': [19],
            'search': ['he will not forgive your transgressions'],
        },
        10: {
            'notes': 'Cursing jealousy',
            'book': 'Deuteronomy',
            'chapter': 29,
            'verse': [20],
            'search': ['god will even blot out your name'],
        },
        11: {
            'notes': 'Global jealousy',
            'book': 'Zechariah',
            'chapter': 1,
            'verse': [14, 15],
            'search': ['god is even jealous of cities'],
        },
        12: {
            'notes': 'Wrathful jealousy',
            'book': 'Zechariah',
            'chapter': 8,
            'verse': [2],
            'search': ['god is even jealous of cities'],
        },
        13: {
            'notes': 'Hot, insulting jealousy',
            'book': 'Ezekiel',
            'chapter': 36,
            'verse': [5, 7],
            'search': ['scream my jealousy from everywhere'],
        },
        14: {
            'notes': 'Seismic jealousy',
            'book': 'Ezekiel',
            'chapter': 38,
            'verse': [19],
            'search': ['god\'s jealousy causes earthquakes'],
        },
        15: {
            'notes': 'Holy jealousy',
            'book': 'Ezekiel',
            'chapter': 39,
            'verse': [25],
            'search': ['god shows mercy to ONE city'],
        },
        16: {
            'notes': 'Provoked jealousy',
            'book': 'Psalm',
            'chapter': 78,
            'verse': [58],
            'search': ['graven images were to blame'],
        },
        17: {
            'notes': 'Long-lasting jealousy',
            'book': 'Psalm',
            'chapter': 79,
            'verse': [5, 6],
            'search': ['people who believe in god want him to punish other kingdoms'],
        },
        18: {
            'notes': 'Spurning jealousy',
            'book': 'Deuteronomy',
            'chapter': 32,
            'verse': [19, 20, 21],
            'search': ['how are his own children perverse if he created them?'],
        },
        19: {
            'notes': 'Furious jealousy',
            'book': 'Ezekiel',
            'chapter': 5,
            'verse': [13],
            'search': ['venting his fury satisfies him'],
        },
        20: {
            'notes': 'Consuming jealousy',
            'book': 'Numbers',
            'chapter': 25,
            'verse': [10, 11],
            'search': ['didn\'t consume Israel in jealousy...?'],
        },
        21: {
            'notes': 'Smoking jealousy',
            'book': 'Deuteronomy',
            'chapter': 29,
            'verse': [20],
            'search': ['even a person\'s name will be blotted out'],
        },
        22: {
            'notes': 'Stranger jealousy',
            'book': 'Deuteronomy',
            'chapter': 32,
            'verse': [16],
            'search': ['god was provoked into jealousy by strange gods'],
        },
        23: {
            'notes': 'Stirred-up jealousy',
            'book': 'Isaiah',
            'chapter': 42,
            'verse': [13],
            'search': ['he\'ll cry and stir up jealousy like a man of war'],
        },
        24: {
            'notes': 'Idol jealousy',
            'book': '1 Kings',
            'chapter': 14,
            'verse': [22, 23],
            'search': ['god is even jealous of images of other gods'],
        },
        25: {
            'notes': 'Image of jealousy',
            'book': 'Ezekiel',
            'chapter': 8,
            'verse': [1, 2, 3, 4],
            'search': ['fire even came from his loins!'],
        },
        26: {
            'notes': 'Generational jealousy',
            'book': 'Deuteronomy',
            'chapter': 5,
            'verse': [9],
            'search': ['punishes the third and fourth generations of children of the people who roused his jealousy'],
        },
    }
}
